DROP DATABASE DIGIBANK

CREATE DATABASE DIGIBANK

USE DIGIBANK

CREATE TABLE Condicoes(
idCondicao TINYINT PRIMARY KEY IDENTITY,
Condicao VARCHAR(20) UNIQUE NOT NULL,
)
GO

CREATE TABLE Usuarios(
idUsuario INT PRIMARY KEY IDENTITY,
NomeCompleto VARCHAR(75) NOT NULL,
Apelido VARCHAR(20),
CPF CHAR(11) UNIQUE,
Telefone CHAR(11) UNIQUE,
Email VARCHAR(255) UNIQUE,
Senha CHAR(60) NOT NULL,
Saldo DECIMAL(11,2),
DigiPoints DECIMAL(8,2),
RendaFixa DECIMAL(8,2) NOT NULL,
)
GO

--CREATE TABLE TipoConta(
--idTipoConta TINYINT PRIMARY KEY IDENTITY,
--TipoConta VARCHAR(15)
--)
--
--CREATE TABLE Conta(
--idConta INT PRIMARY KEY IDENTITY,
--idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario),
--idTipoConta TINYINT FOREIGN KEY REFERENCES TipoConta(idTipoConta) NOT NULL,
--DigiPoints DECIMAL(8,2),
--Saldo DECIMAL (11,2) NOT NULL,
--Senha CHAR(60) NOT NUlL,
--CNPJ CHAR(14) UNIQUE
--)

CREATE TABLE Cartao(
idCartao SMALLINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
Nome VARCHAR(30),
Numero CHAR(16) UNIQUE NOT NULL,
Token CHAR(60) NOT NULL,
CVV CHAR(3) NOT NULL,
isValid BIT NOT NULL,
DataExpira DATETIME NOT NULL,
)
GO

CREATE TABLE Metas(
idMeta SMALLINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario),
Titulo VARCHAR(30) NOT NULL,
ValorMeta DECIMAL(9,2) NOT NULL,
Arrecadado DECIMAL(9,2)
)
GO

CREATE TABLE EmprestimosOptions(
idEmprestimoOption TINYINT PRIMARY KEY IDENTITY,
Valor DECIMAL(9,2) NOT NULL,
TaxaJuros DECIMAL(4,2) NOT NULL,
RendaMinima DECIMAL(8,2) NOT NULL,
PrazoEstimado SMALLINT NOT NULL
)
GO

CREATE TABLE Emprestimos(
idEmprestimo SMALLINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
idCondicao TINYINT FOREIGN KEY REFERENCES Condicoes(idCondicao) NOT NULL,
idEmprestimoOptions TINYINT FOREIGN KEY REFERENCES EmprestimosOptions(idEmprestimoOption) NOT NULL,
ValorPago DECIMAL(9,2),
UltimoPagamento DATETIME,
DataInicial DATETIME NOT NULL,
DataFinal DATETIME
)
GO

CREATE TABLE TipoInvestimentos(
idTipoInvestimento TINYINT PRIMARY KEY IDENTITY,
TipoInvestimento VARCHAR(40) UNIQUE NOT NULL
)
GO

CREATE TABLE AreaInvestimento(
idAreaInvestimento SMALLINT PRIMARY KEY IDENTITY,
Area VARCHAR(45) UNIQUE
)

CREATE TABLE InvestimentoOptions(
idInvestimentoOption SMALLINT PRIMARY KEY IDENTITY,
idTipoInvestimento TINYINT FOREIGN KEY REFERENCES TipoInvestimentos(idTipoInvestimento) NOT NULL,
idAreaInvestimento SMALLINT FOREIGN KEY REFERENCES AreaInvestimento(idAreaInvestimento) NOT NULL,
Nome VARCHAR(45) UNIQUE NOT NULL,
Descricao VARCHAR(700),
Sigla VARCHAR(6) UNIQUE NOT NULL,
Logo VARCHAR(41) NOT NULL,
MainImg VARCHAR(41) NOT NULL,
MainColorHex CHAR(6),
Colaboradores INT NOT NULL,
ValorAcao DECIMAL(13,7) NOT NULL,
QntCotasTotais DECIMAL(14,7) NOT NULL,
Fundacao DATE NOT NULL,
Abertura DATE NOT NULL,
Sede VARCHAR(25) NOT NULL,
Fundador VARCHAR(45) NOT NULL,
PercentualDividendos DECIMAL(4,2),
Tick DATETIME NOT NULL,
--IndiceConfiabilidade DECIMAL(3,2) NOT NULL,
--IndiceDividendos DECIMAL(3,2) NOT NULL,
--IndiceValorizacao DECIMAL(3,2) NOT NULL,
--Talvez isto seja calculado por indices referenciais comparando com outras Options
)
GO

CREATE TABLE HistoricoInvestimentoOption(
idHistorico INT PRIMARY KEY IDENTITY,
idInvestimentoOption SMALLINT FOREIGN KEY REFERENCES InvestimentoOptions(idInvestimentoOption) NOT NULL,
QntCotasDisponiveis DECIMAL(14,7),
DataHistorico DATETIME NOT NULL,
ValorAcao DECIMAL(13,7) NOT NULL
)

CREATE TABLE Investimento(
idInvestimento SMALLINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
idInvestimentoOption SMALLINT FOREIGN KEY REFERENCES InvestimentoOptions(idInvestimentoOption) NOT NULL,
DepositoInicial DECIMAL(9,2) NOT NULL,
QntCotas DECIMAL (13,7) NOT NULL,
DataAquisicao DATETIME NOT NULL,
isEntrada BIT NOT NULL,
)
GO

CREATE TABLE Transacoes(
idTransacao SMALLINT PRIMARY KEY IDENTITY,
idUsuarioPagante INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
idUsuarioRecebente INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
Valor DECIMAL(10,2) NOT NULL,
DataTransacao DATETIME NOT NULL,
Descricao VARCHAR(200)
)
GO

CREATE TABLE Marketplace(
idPost TINYINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
Valor DECIMAL(9,2) NOT NULL,
Nome VARCHAR(55) NOT NULL,
Descricao VARCHAR (700),
isVirtual BIT NOT NULL,
isActive BIT NOT NULL,
Vendas SMALLINT,
QntAvaliacoes SMALLINT,
Avaliacao DECIMAL(3,2),
MainImg VARCHAR(41) NOT NULL,
MainColorHex CHAR(6)
)
GO

CREATE TABLE Avaliacoes(
idAvaliacao INT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario),
idPost TINYINT FOREIGN KEY REFERENCES Marketplace(idPost),
Nota DECIMAL(2,1) NOT NULL,
Replies SMALLINT NOT NULL,
DataPostagem DATETIME NOT NULL,
Comentario VARCHAR(500)
)
GO

CREATE TABLE Curtidas(
idCurtida INT PRIMARY KEY IDENTITY,
idAvaliacao INT FOREIGN KEY REFERENCES Avaliacoes(idAvaliacao) NOT NULL,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
)

CREATE TABLE ImgsPost(
idImg SMALLINT PRIMARY KEY IDENTITY,
idPost TINYINT FOREIGN KEY REFERENCES Marketplace(idPost),
Img VARCHAR(41)
)

CREATE TABLE Inventario(
idInventario SMALLINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario) NOT NULL,
idPost TINYINT FOREIGN KEY REFERENCES Marketplace(idPost) NOT NULL,
Valor DECIMAL(9,2) NOT NULL,
DataAquisicao DATETIME NOT NULL
)

